"""VSCode Claude session management - CLI layer re-exports.

This module re-exports from utils.vscodeclaude for backwards compatibility.
The actual implementation has been moved to utils/vscodeclaude/ for proper
separation of concerns.

See pr_info/steps/architecture_vscodeclaude.md for the architecture details.
"""

# Re-export everything from utils.vscodeclaude for backwards compatibility
from ....utils.vscodeclaude import (  # Types; Constants; Session management; Configuration; Issue filtering; Workspace setup; Orchestration; Status; Cleanup
    DEFAULT_MAX_SESSIONS,
    HUMAN_ACTION_COMMANDS,
    STAGE_DISPLAY_NAMES,
    STATUS_EMOJI,
    VSCODECLAUDE_PRIORITY,
    RepoVSCodeClaudeConfig,
    VSCodeClaudeConfig,
    VSCodeClaudeSession,
    VSCodeClaudeSessionStore,
    add_session,
    check_folder_dirty,
    check_vscode_running,
    cleanup_stale_sessions,
    create_startup_script,
    create_status_file,
    create_vscode_task,
    create_working_folder,
    create_workspace_file,
    delete_session_folder,
    display_status_table,
    get_active_session_count,
    get_eligible_vscodeclaude_issues,
    get_github_username,
    get_human_action_labels,
    get_issue_current_status,
    get_linked_branch_for_issue,
    get_next_action,
    get_session_for_issue,
    get_sessions_file_path,
    get_stage_display_name,
    get_stale_sessions,
    get_working_folder_path,
    handle_pr_created_issues,
    is_issue_closed,
    is_session_stale,
    is_vscode_open_for_folder,
    launch_vscode,
    load_repo_vscodeclaude_config,
    load_sessions,
    load_vscodeclaude_config,
    prepare_and_launch_session,
    process_eligible_issues,
    remove_session,
    restart_closed_sessions,
    run_setup_commands,
    sanitize_folder_name,
    save_sessions,
    setup_git_repo,
    truncate_title,
    update_gitignore,
    update_session_pid,
    validate_mcp_json,
    validate_setup_commands,
)

__all__ = [
    # Types
    "VSCodeClaudeSession",
    "VSCodeClaudeSessionStore",
    "VSCodeClaudeConfig",
    "RepoVSCodeClaudeConfig",
    # Constants
    "VSCODECLAUDE_PRIORITY",
    "HUMAN_ACTION_COMMANDS",
    "STATUS_EMOJI",
    "STAGE_DISPLAY_NAMES",
    "DEFAULT_MAX_SESSIONS",
    # Session management
    "get_sessions_file_path",
    "load_sessions",
    "save_sessions",
    "check_vscode_running",
    "is_vscode_open_for_folder",
    "get_session_for_issue",
    "add_session",
    "remove_session",
    "get_active_session_count",
    "update_session_pid",
    # Configuration
    "load_vscodeclaude_config",
    "load_repo_vscodeclaude_config",
    "get_github_username",
    "sanitize_folder_name",
    # Issue filtering
    "get_human_action_labels",
    "get_eligible_vscodeclaude_issues",
    "get_linked_branch_for_issue",
    # Workspace setup
    "get_working_folder_path",
    "create_working_folder",
    "setup_git_repo",
    "validate_mcp_json",
    "validate_setup_commands",
    "run_setup_commands",
    "update_gitignore",
    "create_workspace_file",
    "create_startup_script",
    "create_vscode_task",
    "create_status_file",
    # Orchestration
    "launch_vscode",
    "get_stage_display_name",
    "truncate_title",
    "prepare_and_launch_session",
    "process_eligible_issues",
    "restart_closed_sessions",
    "handle_pr_created_issues",
    # Status
    "get_issue_current_status",
    "is_issue_closed",
    "is_session_stale",
    "check_folder_dirty",
    "get_next_action",
    "display_status_table",
    # Cleanup
    "get_stale_sessions",
    "delete_session_folder",
    "cleanup_stale_sessions",
]
