#!/usr/bin/env python3
"""Generate architecture documentation from tach analysis.

Creates:
- docs/architecture/dependency_graph.html - Interactive visual diagram
- docs/architecture/dependency_report.html - Detailed dependency report
"""

import subprocess
import sys
from pathlib import Path


def run_command(cmd: list[str]) -> str:
    """Run a command and return stdout."""
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=Path(__file__).parent.parent)
    return result.stdout


def get_mermaid_diagram() -> str:
    """Get mermaid diagram from tach."""
    output = run_command(["tach", "show", "--mermaid", "-o", "-"])
    # Remove the NOTE line at the end
    lines = output.strip().split("\n")
    diagram_lines = []
    for line in lines:
        if line.startswith("NOTE:") or line.startswith("To visualize"):
            break
        diagram_lines.append(line)
    return "\n".join(diagram_lines)


def get_dependency_report(module_path: str) -> str:
    """Get dependency report for a module."""
    output = run_command(["tach", "report", module_path, "--dependencies", "--usages"])
    return output


def generate_graph_html(mermaid_content: str) -> str:
    """Generate the dependency graph HTML."""
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCP Coder - Dependency Graph</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #1a1a2e;
            color: #eee;
        }}
        h1 {{
            text-align: center;
            color: #00d9ff;
            margin-bottom: 10px;
        }}
        .subtitle {{
            text-align: center;
            color: #888;
            margin-bottom: 30px;
        }}
        .legend {{
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }}
        .legend-item {{
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 8px 16px;
            background: #252540;
            border-radius: 8px;
        }}
        .legend-color {{
            width: 16px;
            height: 16px;
            border-radius: 4px;
        }}
        .mermaid {{
            display: flex;
            justify-content: center;
            background: #16213e;
            border-radius: 12px;
            padding: 30px;
            overflow: auto;
        }}
        .info {{
            max-width: 800px;
            margin: 30px auto;
            padding: 20px;
            background: #252540;
            border-radius: 12px;
        }}
        .info h2 {{
            color: #00d9ff;
            margin-top: 0;
        }}
        .info ul {{
            line-height: 1.8;
        }}
        code {{
            background: #1a1a2e;
            padding: 2px 6px;
            border-radius: 4px;
            color: #00d9ff;
        }}
        a {{
            color: #00d9ff;
        }}
    </style>
</head>
<body>
    <h1>MCP Coder - Module Dependency Graph</h1>
    <p class="subtitle">Generated by tach - Architectural Boundary Enforcement | <a href="dependency_report.html">View Detailed Report</a></p>
    
    <div class="legend">
        <div class="legend-item">
            <div class="legend-color" style="background: #ff6b6b;"></div>
            <span>Presentation (CLI)</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background: #4ecdc4;"></div>
            <span>Application (Workflows)</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background: #45b7d1;"></div>
            <span>Domain (LLM, Formatters)</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background: #96ceb4;"></div>
            <span>Infrastructure (Utils)</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background: #dfe6e9;"></div>
            <span>Foundation (Config)</span>
        </div>
    </div>

    <div class="mermaid">
graph TD
    subgraph Presentation
        cli[mcp_coder.cli]
    end
    
    subgraph Application
        workflows[mcp_coder.workflows]
        workflow_utils[mcp_coder.workflow_utils]
    end
    
    subgraph Domain
        llm[mcp_coder.llm]
        formatters[mcp_coder.formatters]
        prompt_manager[mcp_coder.prompt_manager]
    end
    
    subgraph Infrastructure
        utils[mcp_coder.utils]
        mcp_code_checker[mcp_coder.mcp_code_checker]
    end
    
    subgraph Foundation
        config[mcp_coder.config]
        constants[mcp_coder.constants]
    end
    
    root[mcp_coder]
    
    cli --> root
    cli --> workflows
    cli --> workflow_utils
    cli --> llm
    cli --> formatters
    cli --> prompt_manager
    cli --> utils
    cli --> config
    cli --> constants
    cli --> mcp_code_checker
    
    workflows --> workflow_utils
    workflows --> llm
    workflows --> formatters
    workflows --> prompt_manager
    workflows --> utils
    workflows --> config
    workflows --> constants
    
    workflow_utils --> llm
    workflow_utils --> formatters
    workflow_utils --> prompt_manager
    workflow_utils --> utils
    workflow_utils --> config
    workflow_utils --> constants
    
    llm --> utils
    llm --> config
    llm --> constants
    
    formatters --> utils
    formatters --> config
    formatters --> constants
    
    prompt_manager --> utils
    prompt_manager --> config
    prompt_manager --> constants
    
    utils --> config
    utils --> constants
    
    mcp_code_checker --> config
    mcp_code_checker --> constants
    
    root --> llm
    root --> utils
    root --> prompt_manager

    style cli fill:#ff6b6b,stroke:#333,color:#000
    style workflows fill:#4ecdc4,stroke:#333,color:#000
    style workflow_utils fill:#4ecdc4,stroke:#333,color:#000
    style llm fill:#45b7d1,stroke:#333,color:#000
    style formatters fill:#45b7d1,stroke:#333,color:#000
    style prompt_manager fill:#45b7d1,stroke:#333,color:#000
    style utils fill:#96ceb4,stroke:#333,color:#000
    style mcp_code_checker fill:#96ceb4,stroke:#333,color:#000
    style config fill:#dfe6e9,stroke:#333,color:#000
    style constants fill:#dfe6e9,stroke:#333,color:#000
    style root fill:#ffeaa7,stroke:#333,color:#000
    </div>

    <div class="info">
        <h2>Architecture Layers</h2>
        <ul>
            <li><strong>Presentation</strong> - User-facing interfaces (CLI commands)</li>
            <li><strong>Application</strong> - Use cases and workflow orchestration</li>
            <li><strong>Domain</strong> - Core business logic (LLM, formatting, prompts)</li>
            <li><strong>Infrastructure</strong> - Technical implementations (git, github, subprocess)</li>
            <li><strong>Foundation</strong> - Shared constants and configuration</li>
        </ul>
        
        <h2>Commands</h2>
        <ul>
            <li><code>tach check</code> - Verify architectural boundaries</li>
            <li><code>tools\\\\tach_check.bat</code> - Run boundary check</li>
            <li><code>tools\\\\tach_docs.bat</code> - Regenerate this documentation</li>
        </ul>
    </div>

    <script>
        mermaid.initialize({{ 
            startOnLoad: true,
            theme: 'dark',
            flowchart: {{
                useMaxWidth: true,
                htmlLabels: true,
                curve: 'basis'
            }}
        }});
    </script>
</body>
</html>
'''


def generate_report_html(reports: dict[str, str]) -> str:
    """Generate the detailed report HTML."""
    report_sections = []
    for module, report in reports.items():
        escaped_report = report.replace("<", "&lt;").replace(">", "&gt;")
        report_sections.append(f'''
        <div class="module-report">
            <h2>{module}</h2>
            <pre>{escaped_report}</pre>
        </div>
        ''')
    
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCP Coder - Dependency Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #1a1a2e;
            color: #eee;
        }}
        h1 {{
            text-align: center;
            color: #00d9ff;
            margin-bottom: 10px;
        }}
        .subtitle {{
            text-align: center;
            color: #888;
            margin-bottom: 30px;
        }}
        a {{
            color: #00d9ff;
        }}
        .toc {{
            max-width: 800px;
            margin: 0 auto 30px;
            padding: 20px;
            background: #252540;
            border-radius: 12px;
        }}
        .toc h2 {{
            color: #00d9ff;
            margin-top: 0;
        }}
        .toc ul {{
            columns: 2;
            column-gap: 40px;
        }}
        .toc li {{
            margin-bottom: 8px;
        }}
        .module-report {{
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background: #252540;
            border-radius: 12px;
        }}
        .module-report h2 {{
            color: #00d9ff;
            margin-top: 0;
            padding-bottom: 10px;
            border-bottom: 1px solid #444;
        }}
        pre {{
            background: #1a1a2e;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
            font-size: 13px;
            line-height: 1.5;
        }}
    </style>
</head>
<body>
    <h1>MCP Coder - Dependency Report</h1>
    <p class="subtitle">Detailed import-level dependencies and usages | <a href="dependency_graph.html">View Graph</a></p>
    
    <div class="toc">
        <h2>Modules</h2>
        <ul>
            {''.join(f'<li><a href="#{m.replace(".", "-")}">{m}</a></li>' for m in reports.keys())}
        </ul>
    </div>
    
    {''.join(f'<div class="module-report" id="{m.replace(".", "-")}"><h2>{m}</h2><pre>{r.replace("<", "&lt;").replace(">", "&gt;")}</pre></div>' for m, r in reports.items())}
</body>
</html>
'''


def main():
    """Generate architecture documentation."""
    print("Generating architecture documentation...")
    
    # Ensure output directory exists
    output_dir = Path(__file__).parent.parent / "docs" / "architecture"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate dependency graph
    print("  - Generating dependency graph...")
    graph_html = generate_graph_html(get_mermaid_diagram())
    graph_path = output_dir / "dependency_graph.html"
    graph_path.write_text(graph_html, encoding="utf-8")
    print(f"    Created: {graph_path}")
    
    # Generate detailed reports for each module
    print("  - Generating dependency reports...")
    modules = [
        "src/mcp_coder/cli",
        "src/mcp_coder/workflows", 
        "src/mcp_coder/workflow_utils",
        "src/mcp_coder/llm",
        "src/mcp_coder/formatters",
        "src/mcp_coder/utils",
        "src/mcp_coder/config",
    ]
    
    reports = {}
    for module in modules:
        module_name = module.replace("src/", "").replace("/", ".")
        print(f"    - {module_name}")
        reports[module_name] = get_dependency_report(module)
    
    report_html = generate_report_html(reports)
    report_path = output_dir / "dependency_report.html"
    report_path.write_text(report_html, encoding="utf-8")
    print(f"    Created: {report_path}")
    
    print("\nDone! Open docs/architecture/dependency_graph.html to view.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
