name: Test Report

on:
  workflow_run:
    workflows: ['Python CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Download Unit Test Results
      uses: actions/download-artifact@v4
      with:
        name: unit-test-results
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
      continue-on-error: true
        
    - name: Download Integration Test Results
      uses: actions/download-artifact@v4
      with:
        name: integration-test-results
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
      continue-on-error: true
        
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: unit-tests.xml
        reporter: java-junit
        fail-on-error: false
        
    - name: Publish Integration Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Integration Tests
        path: integration-tests.xml
        reporter: java-junit
        fail-on-error: false
